### ISSUE TITLE
Wrong arrows in leaderboard tables?

### ISSUE THREAD

**Issue by martinengelcke** [ecker-lab/object-centric-representation-benchmark#2]
Hi all,

It looks like some of the arrows in the leaderboard tables that indicate whether larger or smaller values are better seem to be wrong?

E.g. there is an upwards arrow for ID S., FPs and MSE, but shouldn't smaller values be better? Similarly, I would think MOTP would need an upwards arrow rather than a downwards error?

Best,
Martin

**Comment by marissaweis** [comment]
Good catch! Fixed it. Thanks!
