### ISSUE TITLE
Loss is negative

### ISSUE THREAD

**Issue by rayeeli** [ecker-lab/object-centric-representation-benchmark#3]
Hi, Thanks for your wonderful work. I have recently been trying to train your ViMON model from scratch. But during training, recons_loss and pred_loss are always negative. So, I would like to ask if it is normal or something wrong?

Best,
Lei

**Comment by marissaweis** [comment]
Hi Lei, thanks for your interest in our work!
ViMON as the static MONet are trained using the decoder negative log-likelihood, therefore the loss is expected to become negative.
Best, Mara

**Comment by rayeeli** [comment]
Thank you for your timely reply!

Best,
Lei
